---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: grafana
  labels:
    app: prometheus-exporter-golang
    component: dashboard
    backend: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      component: dashboard
      backend: grafana
  template:
    metadata:
      labels:
        component: dashboard
        backend: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:5.4.1
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: prometheus-exporter-golang
    component: dashboard
    backend: grafana
  name: grafana
spec:
  type: NodePort
  ports:
  - name: web
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    component: dashboard
    backend: grafana
