---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: prometheus
  labels:
    app: prometheus-exporter-golang
    component: timeseries
    backend: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      component: timeseries
      backend: prometheus
  template:
    metadata:
      creationTimestamp: null
      labels:
        component: timeseries
        backend: prometheus
    spec:
      containers:
        - image: prom/prometheus:v2.5.0
          name: prometheus
          volumeMounts:
            - mountPath: /etc/prometheus/prometheus.yml
              name: config
              subPath: prometheus.yml
      volumes:
        - name: config
          configMap:
            name: prometheus
---
kind: Service
apiVersion: v1
metadata:
  name: prometheus
  labels:
    app: prometheus-exporter-golang
    component: timeseries
    backend: prometheus
spec:
  ports:
    - name: prometheus
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    component: timeseries
    backend: prometheus
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      scrape_timeout: 10s
      evaluation_interval: 15s
    alerting:
      alertmanagers:
      - static_configs:
        - targets: []
        scheme: http
        timeout: 10s
    scrape_configs:
    - job_name: prometheus
      scrape_interval: 15s
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: http
      static_configs:
      - targets:
        - localhost:9090
        - consumer-create-metrics:9000
        - consumer-read-metrics:9000
        - consumer-update-metrics:9000
        - consumer-delete-metrics:9000
