---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: prometheus-exporter-golang
    component: backend
    backend: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      component: backend
      backend: redis
  template:
    metadata:
      labels:
        component: backend
        backend: redis
    spec:
      containers:
        - image: redis:alpine
          name: redis
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: prometheus-exporter-golang
    component: backend
    backend: redis
  name: redis
spec:
  ports:
    - name: tcp
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    component: backend
    backend: redis
  type: ClusterIP
