{
 "title": "Prometherion",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "90% Percentile of successful tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, prometherion_worker_tasks_completed_bucket{success=\"true\"})",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "Rejected tasks",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "prometherion_worker_tasks_error_rejected"
    }
   ]
  },
  {
   "title": "Failed tasks",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "prometherion_worker_tasks_completed_count{success=\"false\"}"
    }
   ]
  }
 ]
}